# Generated by Django 3.1 on 2020-11-02 05:34

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('payroll', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='employee',
            old_name='Address',
            new_name='address',
        ),
        migrations.AddField(
            model_name='employee',
            name='department',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='payroll.department'),
        ),
        migrations.AddField(
            model_name='employee',
            name='full_name',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='employee',
            name='post',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='payroll.post'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='phone',
            field=phonenumber_field.modelfields.PhoneNumberField(blank=True, max_length=128, region=None),
        ),
        migrations.AlterField(
            model_name='holiday',
            name='date',
            field=models.DateField(help_text='a holiday of the year', null=True),
        ),
        migrations.AlterField(
            model_name='holiday',
            name='description',
            field=models.CharField(default='nationally celebrated', help_text='the reason for the holiday', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='holiday',
            name='holiday_name',
            field=models.CharField(default='National holiday', help_text='the name of the holiday', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='leave',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
