# Generated by Django 3.1 on 2020-11-21 16:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('payroll', '0002_salary'),
        ('payroll', '0003_hrprofile'),
    ]

    operations = [
    ]
