# Generated by Django 3.1.3 on 2020-11-23 11:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payroll', '0006_auto_20201122_0211'),
    ]

    operations = [
        migrations.AddField(
            model_name='leave',
            name='accepted',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='leave',
            name='rejected',
            field=models.BooleanField(default=False),
        ),
    ]
