# Generated by Django 3.1.3 on 2020-11-23 15:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('payroll', '0008_remove_employee_gender'),
        ('payroll', '0007_auto_20201123_1654'),
    ]

    operations = [
    ]
