# Generated by Django 3.1.3 on 2020-11-23 15:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('payroll', '0009_merge_20201123_2050'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='leave',
            name='accepted',
        ),
        migrations.RemoveField(
            model_name='leave',
            name='rejected',
        ),
        migrations.AddField(
            model_name='leave',
            name='status',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.CreateModel(
            name='LeaveStatus',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(max_length=100, null=True)),
                ('leaveApp', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='payroll.leave')),
            ],
        ),
    ]
