# Generated by Django 3.1.3 on 2020-11-23 16:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('payroll', '0010_auto_20201123_2054'),
    ]

    operations = [
        migrations.AddField(
            model_name='leave',
            name='to_hr',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='payroll.hrprofile'),
        ),
    ]
