# Generated by Django 3.1.3 on 2020-11-24 02:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payroll', '0011_leave_to_hr'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hrprofile',
            name='profile_pic',
            field=models.ImageField(blank=True, default='images/profile/default2.jpg', upload_to='images/profile'),
        ),
    ]
