# Generated by Django 3.1 on 2020-11-24 03:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('payroll', '0011_leave_to_hr'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Holiday',
        ),
    ]
