# Generated by Django 3.1.3 on 2020-11-24 06:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('payroll', '0012_delete_holiday'),
        ('payroll', '0012_auto_20201124_0826'),
    ]

    operations = [
    ]
