# Generated by Django 3.1 on 2020-11-24 08:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payroll', '0013_merge_20201124_1131'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='profile_pic',
            field=models.ImageField(blank=True, default='images/profile/default2.jpg', upload_to='images/profile'),
        ),
    ]
